# This is a basic workflow to help you get started with Actions

name: Spell check

# Controls when the workflow will run
on:
  workflow_call:
  schedule:
    # Trigger Codespell at a scheduled time
    # * is a special character in YAML so you have to quote this string
    - cron: '30 0 * * *'
  # Triggers the workflow on push or pull request events
 # push:
  #  branches:
  #  - 'master'
  pull_request:
    branches:
    - 'master'
    - '*typo*'
    - '*spell*'
  # Trigger the workflow when dict files or this workflow file been changed
  push:
    paths:
      - '.github/workflows/codespell.yml'
      - '.github/codespell/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Codespell"
  Codespell:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.codespell.outputs.RESULT }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v5
    
      - name: Install Codespell
        run: |
          pip install codespell

      - name: Set up dictionaries
        run: |
          wget -q https://raw.githubusercontent.com/codespell-project/codespell/master/codespell_lib/data/dictionary.txt
          wget -q https://raw.githubusercontent.com/codespell-project/codespell/master/codespell_lib/data/dictionary_rare.txt
          wget -q https://raw.githubusercontent.com/codespell-project/codespell/master/codespell_lib/data/dictionary_code.txt
          mv .github/codespell/dictionary_cust.txt ./
  
      - name: Run Codespell
        id: codespell
        env:
          skipList: "./.git,./.github/workflows/codespell.yml,./dictionary*.txt,./Sandboxie/msgs/Text-*-*.txt,./Sandboxie/msgs/report/Report-*.txt,./SandboxiePlus/SandMan/*.ts,./Installer/Languages.iss,./Installer/isl/*.isl,./SandboxiePlus/SandMan/Troubleshooting/lang_*.json,./Sandboxie/install/build.bat,./SandboxieTools/ImBox/dc/crypto_fast/xts_fast.c,./Sandboxie/install/SbieSettings.ini"
          ignoreWordsList: "wil,unknwn,tolen,pevent,doubleclick,parm,parms,etcp,ois,ba,ptd,modell,namesd,stdio,uint,errorstring,ontext,atend,deque,ecounter,nmake,namess,inh,daa,varient,lite,uis,emai,ws,slanguage,woh,tne,typpos,enew,shft,seh,ser,servent,socio-economic,rime,falt,infor,vor,lets,od,fo,aas,shs,focusin,readded,clen,numer,"
        run: |
            # Only lowercase letters are allowed in --ignore-words-list
            codespell --dictionary=dictionary.txt --dictionary=dictionary_rare.txt --dictionary=dictionary_code.txt --dictionary=dictionary_cust.txt \
              --ignore-words-list="$ignoreWordsList" \
              --skip="$skipList" > codespell.log
            cat codespell.log
            {
              echo "RESULT<<EOF"
              cat codespell.log
              echo EOF
            } >> "$GITHUB_OUTPUT"

            
  Comments:
    if: ${{ failure() && github.event_name == 'pull_request' }}
    needs: Codespell
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write 
    steps:
      - name: Create PR comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Codespell may found some possible typos
            <details>
            <summary>Click to expand</summary>

            ``` 
            ${{ needs.Codespell.outputs.result }}
            ```
            </details>
            _This comment was created automatically by a GitHub Action._